config/routes.rb
Rails.application.routes.draw do
  resources :products
  get 'simple_pages/index'
  root 'simple_pages#landing_page'
  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'products/index'
  get 'simple_pages/landing_page'
  resources :orders, only: [:index, :show, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.includes(:product).all
  end

  def Show
    @order = Order.find(params[:id])
  end

  def new
  end

  def create
  end

  def destroy
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController
  def index
  end
  def about
  end
  def contact
  end
  def landing_page
    @products = Product.limit(3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>

    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

  </head>

  <body>
  <!--  <nav>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", simple_pages_about_path %></li>
      <li><%= link_to "Contact", simple_pages_contact_path %></li>
    </ul>
  </nav>
  Hide Navbar in cases of danger, and things happen... -->

  <nav class="navbar navbar-light navbar-expand-md rounded-0" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand"><%= link_to 'Bike Berlin', root_path %></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'Home', simple_pages_index_path %></li>
        <li><%= link_to 'About', simple_pages_about_path %></li>
        <li><%= link_to 'Contact', simple_pages_contact_path %></li>
        <li><%= link_to 'Products', products_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </div>
</nav>

    <%= yield %>

    <footer style="background-color: #e3f2fd;">
  &copy; 2018 Bike Berlin
</footer>
  </body>
</html>

app/views/orders/index.html.erb
<div class="row">
  <% @orders.each do |order| %>
    <div class="col-sm">
      <h1>
        Order # <%= order.id %>:
        <%= link_to order.product.name, order %>
      </h1>
      <p><%= order.product.description %></p>
      <strong>$ <%= order.product.price %></strong>
    </div><!-- /col -->
  <% end %>
</div>

app/views/orders/show.html.erb
<div class="container">
  <h2>Order Information</h2>
  <strong>Order ID: </strong><%= @order.id %>
  <strong>Product Name: </strong><%= @order.product.name %>
  <strong>Product Price: </strong><%= number_to_currency(@order.product.price/100.to_f) %>
  <strong>Total Price: </strong><%= number_to_currency(@order.total/100.to_f) %>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :colour %><br>
    <%= form.text_field :colour %>
  </div>

  <div class="field">
    <%= form.label :price %><br>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<a href="#"><h1><%= product.name %></h1></a>
<p><%= image_tag(product.image_url, class: "img-fluid", :width => "100%") %></p>
<p><%= product.description %></p>
<p><%= product.colour %></p>
<strong><%= product.price %></strong>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<!--
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Colour</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= image_tag(product.image_url, :width => "100%") %></td>
        <td><%= product.colour %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
-->

<div class="container-fluid">
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-sm-12 col-md-4">
        <%= render product %>
      </div><!-- /col -->
    <% end %>
  </div>
</div>
<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Colour:</strong>
  <%= @product.colour %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/simple_pages/about.html.erb
<h1>SimplePages#about</h1>
<h1>About Bike Berlin</h1>
<p>Founded on the 21.06.2018 with the help of a patient tutor </br>
  SiilenceBlack opened his gates to all the bikers out there. </br>
  Cause we all know, guys in suits love bikes!
</p>
<p>Find me in app/views/simple_pages/about.html.erb</p>

app/views/simple_pages/contact.html.erb
<h1>SimplePages#contact</h1>
<h1>Contact Bike Berlin</h1>
<ul>
  <li>Phone Number</li>
  <li>Mail address</li>
  <li>Street, Town</li>
</ul>
<p>Find me in app/views/simple_pages/contact.html.erb</p>

app/views/simple_pages/index.html.erb
<h1>SimplePages#index</h1>
<h1>Welcome to Bike Berlin </h1>
<h2>Your source for used bikes in Berlin</h2>
<p>Welcome! The date and time is <%= Time.now %></p>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4 col-sm-6 col-xs-12">
      <%= image_tag("beach_bike.jpg", class:"img-responsive my-image", size:"cover") %>
    </div>
  </div>
</div>
<!-- <%# test_variable = 42 %>
<%#= test_variable %>
WOOHOO i can put variables in my html by using ERB tags
If i want to comment out ERB tags i´ll have to use ruby
if i use the #, ERB tags will no longer execute-->

<p>Find me in app/views/simple_pages/index.html.erb</p>

app/views/simple_pages/landing_page.html.erb
<div class="container-fluid">
  <div id="carousel-image" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <% @products.length.times do |i| %>
      <li data-target="#carousel-image" data-slide-to="<%= i.to_s %>" class="<%= 'active' if i == 0 %>">
      </li>
      <% end %>
    </ol>
    <div class="carousel-inner" role="listbox">
      <% @products.each do |product| %>
      <div class="carousel-item<%= " active" if product == @products.first %>">
        <%= image_tag(product.image_url, class: "img-fluid", :width => "100%") %>
        <div class="carousel-caption">
          <%= product.name %>
        </div>
      </div>
    </div>
      <% end %>
  </div>

  <a class="carousel-control-prev" href="#carousel-image" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carousel-image" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>